services:
  db:
    image: postgres:17
    environment:
      'POSTGRES_DB': '${DATABASE}'
      'POSTGRES_PASSWORD': '${PASSWORD}'
      'POSTGRES_USER': '${USERNAME}'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  
  api:
    image: api
    build:
      context: ./Backend/SpendLens
      dockerfile: SpendLensApi/Dockerfile
    environment:
      'ConnectionStrings__DefaultConnection': 'Host=db;Port=5432;Database=${DATABASE};Username=${USERNAME};Password=${PASSWORD};'
  
  worker:
    image: worker
    build:
      context: ./Worker
      dockerfile: Dockerfile
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    restart: always

volumes:
  pgdata:
  minio_data: